name: Build and test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with testing
      run: ./gradlew --stacktrace test jruby9_1_15Test jruby9_1_17Test jruby9_2_0Test jruby9_2_9Test build
  crubyTest:
    strategy:
      matrix:
        ruby: [2.4.x, 2.5.x, 2.6.x]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Build with testing
      run: ./gradlew crubyTest
