name: Check
on: [ pull_request, push ]
jobs:
  check:
    runs-on: ubuntu-latest
    # push: always run.
    # pull_request: run only when the PR is submitted from a forked repository, not within this repository.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up OpenJDK 8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: "temurin"
        cache: "gradle"
    - name: Check on Java
      run: ./gradlew --stacktrace test jruby9_1_15Test jruby9_1_17Test jruby9_2_0Test jruby9_2_9Test
  crubyTest:
    runs-on: ubuntu-latest
    # push: always run.
    # pull_request: run only when the PR is submitted from a forked repository, not within this repository.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.4.10, 2.5.9, 2.6.10, 2.7.7, 3.0.5, 3.1.3, 3.2.1]
    steps:
    - uses: actions/checkout@v3
    - name: Set up OpenJDK 8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: "temurin"
        cache: "gradle"
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Check with CRuby
      run: ./gradlew crubyTest
